import type { MonthlyItem, OneOffItem, UnreviewedItem, VariableItem } from './persona';

export const MonthlyIncome: readonly MonthlyItem[] = [
  {
    account: 'usd',
    amountMinor: [20_000, 34_000],
    category: 'Freelance & side income',
    day: 20,
    memo: 'Photo licensing royalties',
    payee: 'Lumen Stock',
  },
];

export const MonthlyBills: readonly MonthlyItem[] = [
  {
    account: 'everyday',
    amountMinor: [120_000, 120_000],
    category: 'Rent / Mortgage',
    day: 1,
    memo: 'Rent',
    payee: 'Oakwood Lettings',
  },
  {
    account: 'everyday',
    amountMinor: [4000, 4000],
    category: 'Public transit',
    day: 2,
    memo: 'Monthly travel pass',
    payee: 'City Transit',
  },
  {
    account: 'creditCard',
    amountMinor: [3500, 3500],
    category: 'Fitness',
    day: 3,
    memo: 'Gym membership',
    payee: 'PulseFit Gym',
  },
  {
    account: 'creditCard',
    amountMinor: [1299, 1299],
    category: 'Streaming',
    day: 5,
    latestChargeMinor: 1399,
    memo: 'Standard plan',
    payee: 'Netflix',
  },
  {
    account: 'everyday',
    amountMinor: [4000, 8000],
    category: 'Electricity & gas',
    day: 8,
    memo: 'Electricity',
    payee: 'BrightSpark Energy',
  },
  {
    account: 'creditCard',
    activeUntilOffset: -4,
    amountMinor: [1099, 1099],
    category: 'Music',
    day: 9,
    memo: 'Premium',
    payee: 'Spotify',
  },
  {
    account: 'creditCard',
    activeFromOffset: -3,
    amountMinor: [1199, 1199],
    category: 'Music',
    day: 9,
    memo: 'Premium',
    payee: 'Spotify',
  },
  {
    account: 'everyday',
    amountMinor: [4000, 8000],
    category: 'Electricity & gas',
    day: 12,
    memo: 'Gas',
    payee: 'Hearth Gas',
  },
  {
    account: 'everyday',
    amountMinor: [2500, 2500],
    category: 'Internet & TV',
    day: 15,
    memo: 'Fibre 600 Mb',
    payee: 'FibreNet',
  },
  {
    account: 'everyday',
    amountMinor: [1500, 1500],
    category: 'Mobile phone',
    day: 18,
    memo: 'Mobile plan',
    payee: 'Mobi Mobile',
  },
  {
    account: 'usd',
    amountMinor: [2500, 4500],
    category: 'Professional services',
    day: 22,
    memo: 'Advisory fee',
    payee: 'Harbor Financial Advice',
  },
];

export const VariableSpending: readonly VariableItem[] = [
  {
    account: 'everyday',
    amountMinor: [2000, 7500],
    category: 'Groceries',
    days: [2, 6, 9, 13, 17, 20, 24, 28],
    name: 'groceries',
    payees: ['Greenleaf Market', 'Greenleaf Market', 'FreshCo'],
    probability: 1,
  },
  {
    account: 'cash',
    amountMinor: [250, 450],
    category: 'Coffee',
    days: [3, 10, 17, 24],
    name: 'coffee',
    payees: ['Corner Café'],
    probability: 0.9,
  },
  {
    account: 'cash',
    amountMinor: [300, 800],
    category: 'Groceries',
    days: [6, 20],
    name: 'bakery',
    payees: ['Village Bakery'],
    probability: 0.8,
  },
  {
    account: 'creditCard',
    amountMinor: [1800, 6500],
    category: 'Restaurants & bars',
    days: [7, 16, 25],
    name: 'restaurants',
    payees: ["Luigi's Trattoria", 'Sakura Sushi', 'The Brass Tap'],
    probability: 0.9,
  },
  {
    account: 'creditCard',
    amountMinor: [1500, 3200],
    category: 'Takeout & delivery',
    days: [11, 23],
    name: 'takeout',
    payees: ['QuickBite Delivery'],
    probability: 0.8,
  },
  {
    account: 'creditCard',
    amountMinor: [800, 2200],
    category: 'Taxi & rideshare',
    days: [19],
    name: 'taxi',
    payees: ['RideNow'],
    probability: 0.7,
  },
  {
    account: 'creditCard',
    amountMinor: [2500, 9000],
    category: 'Clothing',
    days: [12],
    name: 'clothing',
    payees: ['Urban Threads'],
    probability: 0.7,
  },
  {
    account: 'creditCard',
    amountMinor: [1800, 1800],
    category: 'Personal care',
    days: [21],
    name: 'haircut',
    payees: ['Fade & Co Barbers'],
    probability: 1,
  },
  {
    account: 'creditCard',
    amountMinor: [600, 2500],
    category: 'Pharmacy',
    days: [9],
    name: 'pharmacy',
    payees: ['Wellness Pharmacy'],
    probability: 0.5,
  },
  {
    account: 'creditCard',
    amountMinor: [900, 2400],
    category: 'Movies & events',
    days: [27],
    name: 'cinema',
    payees: ['Starlight Cinema'],
    probability: 0.6,
  },
  {
    account: 'creditCard',
    amountMinor: [1200, 3500],
    category: 'Books & hobbies',
    days: [15],
    name: 'books',
    payees: ['Paper Lantern Books'],
    probability: 0.4,
  },
];

export const OneOffPurchases: readonly OneOffItem[] = [
  {
    account: 'creditCard',
    amountMinor: -109_900,
    category: 'Electronics',
    day: 6,
    memo: 'New laptop',
    monthOffset: -21,
    payee: 'TechNest',
  },
  {
    account: 'everyday',
    amountMinor: -64_900,
    category: 'Furniture & decor',
    day: 18,
    memo: 'Sofa',
    monthOffset: -16,
    payee: 'Nordic Home',
  },
  {
    account: 'everyday',
    amountMinor: 12_000,
    category: 'Refunds & reimbursements',
    day: 23,
    memo: 'Deposit returned from the old flat',
    monthOffset: -15,
    payee: 'Oakwood Lettings',
  },
  {
    account: 'everyday',
    amountMinor: -9500,
    category: 'Education',
    day: 8,
    memo: 'Photography workshop',
    monthOffset: -10,
    payee: 'City Photo School',
  },
  {
    account: 'creditCard',
    amountMinor: -21_900,
    category: 'Electronics',
    day: 11,
    memo: 'Noise-cancelling headphones',
    monthOffset: -5,
    payee: 'TechNest',
  },
  {
    account: 'creditCard',
    amountMinor: 3500,
    category: 'Clothing',
    day: 19,
    memo: 'Returned jacket',
    monthOffset: -4,
    payee: 'Urban Threads',
  },
  {
    account: 'creditCard',
    amountMinor: -18_900,
    category: 'Flights',
    day: 3,
    memo: 'Lisbon weekend',
    monthOffset: -3,
    payee: 'SkyHop Airlines',
  },
  {
    account: 'creditCard',
    amountMinor: -24_600,
    category: 'Lodging',
    day: 20,
    memo: 'Lisbon weekend',
    monthOffset: -3,
    payee: 'Harbour View Hotel',
  },
  {
    account: 'creditCard',
    amountMinor: -4500,
    category: 'Vacation activities',
    day: 21,
    memo: 'Lisbon weekend',
    monthOffset: -3,
    payee: 'Tram & Tour',
  },
  {
    account: 'creditCard',
    amountMinor: -6000,
    category: 'Gifts',
    day: 14,
    memo: 'Birthday present for Ana',
    monthOffset: -2,
    payee: 'Giftology',
  },
  {
    account: 'everyday',
    amountMinor: -8500,
    category: 'Doctor & dental',
    day: 7,
    memo: 'Check-up and cleaning',
    monthOffset: -1,
    payee: 'Smile Dental',
  },
];

export const UnreviewedPurchases: readonly UnreviewedItem[] = [
  {
    account: 'creditCard',
    amountMinor: -2399,
    bankDescription: 'MKTPLACE*7731 ONLINE',
    daysAgo: 1,
  },
  {
    account: 'everyday',
    amountMinor: -1250,
    bankDescription: 'SQ *FARMERS STALL',
    daysAgo: 2,
  },
];

export const MonthlyBudgets: readonly { amountMinor: number; category: string }[] = [
  { amountMinor: 6000, category: 'Home & garden' },
  { amountMinor: 35_000, category: 'Groceries' },
  { amountMinor: 15_000, category: 'Restaurants & bars' },
  { amountMinor: 6000, category: 'Takeout & delivery' },
  { amountMinor: 1500, category: 'Coffee' },
  { amountMinor: 15_000, category: 'Electricity & gas' },
  { amountMinor: 8000, category: 'Clothing' },
  { amountMinor: 2500, category: 'Streaming' },
  { amountMinor: 2000, category: 'Taxi & rideshare' },
];

export const DemoRules: readonly { category: string; name: string; pattern: string }[] = [
  {
    category: 'Groceries',
    name: 'Greenleaf is groceries',
    pattern: 'greenleaf',
  },
  {
    category: 'Streaming',
    name: 'Netflix is streaming',
    pattern: 'netflix',
  },
  {
    category: 'Music',
    name: 'Spotify is music',
    pattern: 'spotify',
  },
  {
    category: 'Public transit',
    name: 'City Transit is transit',
    pattern: 'city transit',
  },
  {
    category: 'Takeout & delivery',
    name: 'QuickBite is takeout',
    pattern: 'quickbite',
  },
];
