import {
  siAirbnb,
  siAnthropic,
  siApple,
  siApplemusic,
  siAppletv,
  siAudible,
  siBookingdotcom,
  siBurgerking,
  siCarrefour,
  siDeezer,
  siDeliveroo,
  siDiscord,
  siDropbox,
  siDuolingo,
  siEasyjet,
  siEbay,
  siEtsy,
  siGithub,
  siGlovo,
  siGoogle,
  siGooglepay,
  siHbo,
  siIcloud,
  siIkea,
  siKfc,
  siLidl,
  siLyft,
  siMcdonalds,
  type SimpleIcon,
  siN26,
  siNetflix,
  siNotion,
  siOrange,
  siPatreon,
  siPaypal,
  siPlaystation,
  siRevolut,
  siRyanair,
  siShell,
  siSpotify,
  siStarbucks,
  siSteam,
  siStrava,
  siTarget,
  siTesco,
  siTicketmaster,
  siTidal,
  siTwitch,
  siUber,
  siUbereats,
  siUnitedairlines,
  siVodafone,
  siWise,
  siYoutube,
  siZara,
  siZoom,
} from 'simple-icons';

export type BrandIcon = Pick<SimpleIcon, 'hex' | 'path' | 'title'>;

export const BrandIcons: Record<string, BrandIcon> = {
  airbnb: siAirbnb,
  anthropic: siAnthropic,
  apple: siApple,
  applemusic: siApplemusic,
  appletv: siAppletv,
  audible: siAudible,
  booking: siBookingdotcom,
  burgerking: siBurgerking,
  carrefour: siCarrefour,
  deezer: siDeezer,
  deliveroo: siDeliveroo,
  discord: siDiscord,
  dropbox: siDropbox,
  duolingo: siDuolingo,
  easyjet: siEasyjet,
  ebay: siEbay,
  etsy: siEtsy,
  github: siGithub,
  glovo: siGlovo,
  google: siGoogle,
  googlepay: siGooglepay,
  hbo: siHbo,
  icloud: siIcloud,
  ikea: siIkea,
  kfc: siKfc,
  lidl: siLidl,
  lyft: siLyft,
  mcdonalds: siMcdonalds,
  n26: siN26,
  netflix: siNetflix,
  notion: siNotion,
  orange: siOrange,
  patreon: siPatreon,
  paypal: siPaypal,
  playstation: siPlaystation,
  revolut: siRevolut,
  ryanair: siRyanair,
  shell: siShell,
  spotify: siSpotify,
  starbucks: siStarbucks,
  steam: siSteam,
  strava: siStrava,
  target: siTarget,
  tesco: siTesco,
  ticketmaster: siTicketmaster,
  tidal: siTidal,
  twitch: siTwitch,
  uber: siUber,
  ubereats: siUbereats,
  unitedairlines: siUnitedairlines,
  vodafone: siVodafone,
  wise: siWise,
  youtube: siYoutube,
  zara: siZara,
  zoom: siZoom,
};
